export const CODE_SUCCESS = 200;

export const API_DOES_NOT_EXIT = "API does not exist";

export const STATUS = ["", "open", "inprogress", "close"];
export const STATUS_CATEGORY = ["", "Enable", "Disable"];
export const STATUS_CLOSE = 2;

export const LIST_REQUEST = "LIST_REQUEST";
export const START_GET_LIST_REQUEST = "START_GET_LIST_REQUEST";
export const END_GET_LIST_REQUEST = "END_GET_LIST_REQUEST";
export const GET_LIST_REQUEST_SUCCESS = "GET_LIST_REQUEST_SUCCESS";
export const GET_LIST_REQUEST_FAIL = "GET_LIST_REQUEST_FAIL";

export const REQUEST_DETAIL = "REQUEST_DETAIL";
export const GET_REQUEST_DETAIL_SUCCESS = "GET_REQUEST_DETAIL_SUCCESS";
export const GET_REQUEST_DETAIL_FAIL = "GET_REQUEST_DETAIL_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT";

export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const POST_COMMENT = "POST_COMMENT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const POST_USER = "POST_USER";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAIL = "POST_USER_FAIL";

export const FILTERS_REQUEST = "FILTERS_REQUEST";
export const FILTERS_REQUEST_SUCCESS = "FILTERS_REQUEST_SUCCESS";

export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS";
export const ADD_REQUEST_FAIL = "ADD_REQUEST_FAIL";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const POST_CATEGORY = "POST_CATEGORY";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_FAIL = "POST_CATEGORY_FAIL";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const GET_ASSIGNEE = "GET_ASSIGNEE";
export const GET_ASSIGNEE_SUCCESS = "GET_ASSIGNEE_SUCCESS";
export const GET_ASSIGNEE_FAIL = "GET_ASSIGNEE_FAIL";

export const HISTORY = "HISTORY";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAIL = "GET_HISTORY_FAIL";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_FAIL = "UPDATE_REQUEST_FAIL";
